# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
  - OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.2-solc-0.7
  - Uniswap/uniswap-v3-core@1.0.0
  - Uniswap/uniswap-v3-periphery@1.0.0
  - OpenZeppelin/openzeppelin-contracts@3.4.2


# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.7.6
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2'
      - '@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.2-solc-0.7'
      - "@uniswap/v3-core=Uniswap/uniswap-v3-core@1.0.0"
      - "@uniswap/v3-periphery=Uniswap/uniswap-v3-periphery@1.0.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.2"


reports:
